package DesimpenhoApp;


/**
* DesimpenhoApp/DesimpenhoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Desimpenho.idl
* Segunda-feira, 17 de Fevereiro de 2014 05h04min19s GMT-03:00
*/

public abstract class DesimpenhoPOA extends org.omg.PortableServer.Servant
 implements DesimpenhoApp.DesimpenhoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("desimpenho", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DesimpenhoApp/Desimpenho/desimpenho
       {
         double $result = (double)0;
         $result = this.desimpenho ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DesimpenhoApp/Desimpenho:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Desimpenho _this() 
  {
    return DesimpenhoHelper.narrow(
    super._this_object());
  }

  public Desimpenho _this(org.omg.CORBA.ORB orb) 
  {
    return DesimpenhoHelper.narrow(
    super._this_object(orb));
  }


} // class DesimpenhoPOA
