package DesimpenhoApp;


/**
* DesimpenhoApp/Desimpenho.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Desimpenho.idl
* Segunda-feira, 17 de Fevereiro de 2014 05h04min19s GMT-03:00
*/

public interface Desimpenho extends DesimpenhoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Desimpenho
