package DesimpenhoApp;


/**
* DesimpenhoApp/DesimpenhoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Desimpenho.idl
* Segunda-feira, 17 de Fevereiro de 2014 05h04min19s GMT-03:00
*/

abstract public class DesimpenhoHelper
{
  private static String  _id = "IDL:DesimpenhoApp/Desimpenho:1.0";

  public static void insert (org.omg.CORBA.Any a, DesimpenhoApp.Desimpenho that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DesimpenhoApp.Desimpenho extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DesimpenhoApp.DesimpenhoHelper.id (), "Desimpenho");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DesimpenhoApp.Desimpenho read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DesimpenhoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DesimpenhoApp.Desimpenho value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DesimpenhoApp.Desimpenho narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DesimpenhoApp.Desimpenho)
      return (DesimpenhoApp.Desimpenho)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DesimpenhoApp._DesimpenhoStub stub = new DesimpenhoApp._DesimpenhoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DesimpenhoApp.Desimpenho unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DesimpenhoApp.Desimpenho)
      return (DesimpenhoApp.Desimpenho)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DesimpenhoApp._DesimpenhoStub stub = new DesimpenhoApp._DesimpenhoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
